apiVersion: v1
kind: Service
metadata:
  name: another-awesome-app
  namespace: default
  labels:
    app: another-awesome-app
    managed-by: kratix
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: another-awesome-app
