apiVersion: v1
kind: Service
metadata:
  name: awesome-api-api
  namespace: default
  labels:
    app: awesome-api-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: awesome-api-api
