apiVersion: v1
kind: Service
metadata:
  name: my-awesome-app-redis
  namespace: default
  labels:
    app: my-awesome-app-redis
    managed-by: kratix
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: my-awesome-app-redis
