apiVersion: v1
kind: Secret
metadata:
  name: another-api-db-credentials
  namespace: default
type: Opaque
data:
  postgres-password: Y2hhbmdlbWUxMjM=
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmNoYW5nZW1lMTIzQGFub3RoZXItYXBpLXBvc3RncmVzOjU0
MzIvYW5vdGhlci1hcGk=
